name: Testing
on: push

jobs:
    test_project:
        runs-on: ubuntu-latest
        steps:
          - name: Setup Python
            uses: actions/setup-python@main
            with:
              python-version: "3.12"
              architecture: "x64"

          - name: Setup Python
            run:
              pip install uv
              uv sync

          - uses: actions/checkout@main
          - name: Run Django unit tests
            run:
              uv run manage.py test
