name: Testing
on: push

jobs:
    test_project:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@main
          - name: Run Django unit tests
            run:
                pip install --user django
                python manage.py test
