name: Testing CI/CD
on: push

jobs:
    test_project:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@main

          - name: "Install uv"
            uses: astral-sh/setup-uv@main

          - name: "Set up Python"
            uses: actions/setup-python@main
            with:
              python-version-file: ".python-version"

          - name: "Run Django unit tests"
            run:
              echo "${{secrets.env }}" > .env
              uv run manage.py test
